# Base de datos
spring.datasource.url=jdbc:postgresql://localhost:5432/taskmanager_db
spring.datasource.username=postgres
spring.datasource.password=Candelaria97

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Puerto de la app
server.port=8080

# JWT
jwt.secret=taskmanager_secret_key_super_segura_2024_debe_ser_larga
jwt.expiration=86400000

# CORS (para frontend local y despliegue)
# Separado por comas
app.cors.allowed-origins=http://localhost:5173,http://localhost:3000